name: flutter_tutofast
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  hive: ^1.4.4+1
  get: ^3.10.2
  hive_flutter: ^0.3.1
  path_provider: ^1.6.5
  auto_size_text: ^2.1.0
  flutter_form_bloc: ^0.19.0
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

flutter_launcher_name: 
  name: 'TutoFast'

flutter_icons:
  image_path: 'assets/images/icons/ICON.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/objects/
    - assets/images/backgrounds/

  fonts:
    - family: AfterNight
      fonts:
        - asset: assets/fonts/AfterNight.ttf
          weight: 400

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/CenturyGothic-Regular.ttf
          weight: 500
        - asset: assets/fonts/CenturyGothic-Bold.ttf
          weight: 500